package bplustree

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *InteriorNode) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Kcs":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Kcs")
				return
			}
			if cap(z.Kcs) >= int(zb0002) {
				z.Kcs = (z.Kcs)[:zb0002]
			} else {
				z.Kcs = make(KCs, zb0002)
			}
			for za0001 := range z.Kcs {
				var zb0003 uint32
				zb0003, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "Kcs", za0001)
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "Kcs", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "Key":
						z.Kcs[za0001].Key, err = dc.ReadBytes(z.Kcs[za0001].Key)
						if err != nil {
							err = msgp.WrapError(err, "Kcs", za0001, "Key")
							return
						}
					case "Child":
						err = z.Kcs[za0001].Child.DecodeMsg(dc)
						if err != nil {
							err = msgp.WrapError(err, "Kcs", za0001, "Child")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "Kcs", za0001)
							return
						}
					}
				}
			}
		case "Count":
			z.Count, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Count")
				return
			}
		case "P":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "P")
					return
				}
				z.P = nil
			} else {
				if z.P == nil {
					z.P = new(InteriorNode)
				}
				err = z.P.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "P")
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *InteriorNode) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 3
	// write "Kcs"
	err = en.Append(0x83, 0xa3, 0x4b, 0x63, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Kcs)))
	if err != nil {
		err = msgp.WrapError(err, "Kcs")
		return
	}
	for za0001 := range z.Kcs {
		// map header, size 2
		// write "Key"
		err = en.Append(0x82, 0xa3, 0x4b, 0x65, 0x79)
		if err != nil {
			return
		}
		err = en.WriteBytes(z.Kcs[za0001].Key)
		if err != nil {
			err = msgp.WrapError(err, "Kcs", za0001, "Key")
			return
		}
		// write "Child"
		err = en.Append(0xa5, 0x43, 0x68, 0x69, 0x6c, 0x64)
		if err != nil {
			return
		}
		err = z.Kcs[za0001].Child.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Kcs", za0001, "Child")
			return
		}
	}
	// write "Count"
	err = en.Append(0xa5, 0x43, 0x6f, 0x75, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Count)
	if err != nil {
		err = msgp.WrapError(err, "Count")
		return
	}
	// write "P"
	err = en.Append(0xa1, 0x50)
	if err != nil {
		return
	}
	if z.P == nil {
		err = en.WriteNil()
		if err != nil {
			return
		}
	} else {
		err = z.P.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "P")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *InteriorNode) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	// string "Kcs"
	o = append(o, 0x83, 0xa3, 0x4b, 0x63, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Kcs)))
	for za0001 := range z.Kcs {
		// map header, size 2
		// string "Key"
		o = append(o, 0x82, 0xa3, 0x4b, 0x65, 0x79)
		o = msgp.AppendBytes(o, z.Kcs[za0001].Key)
		// string "Child"
		o = append(o, 0xa5, 0x43, 0x68, 0x69, 0x6c, 0x64)
		o, err = z.Kcs[za0001].Child.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Kcs", za0001, "Child")
			return
		}
	}
	// string "Count"
	o = append(o, 0xa5, 0x43, 0x6f, 0x75, 0x6e, 0x74)
	o = msgp.AppendInt(o, z.Count)
	// string "P"
	o = append(o, 0xa1, 0x50)
	if z.P == nil {
		o = msgp.AppendNil(o)
	} else {
		o, err = z.P.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "P")
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *InteriorNode) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Kcs":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Kcs")
				return
			}
			if cap(z.Kcs) >= int(zb0002) {
				z.Kcs = (z.Kcs)[:zb0002]
			} else {
				z.Kcs = make(KCs, zb0002)
			}
			for za0001 := range z.Kcs {
				var zb0003 uint32
				zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Kcs", za0001)
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "Kcs", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "Key":
						z.Kcs[za0001].Key, bts, err = msgp.ReadBytesBytes(bts, z.Kcs[za0001].Key)
						if err != nil {
							err = msgp.WrapError(err, "Kcs", za0001, "Key")
							return
						}
					case "Child":
						bts, err = z.Kcs[za0001].Child.UnmarshalMsg(bts)
						if err != nil {
							err = msgp.WrapError(err, "Kcs", za0001, "Child")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "Kcs", za0001)
							return
						}
					}
				}
			}
		case "Count":
			z.Count, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Count")
				return
			}
		case "P":
			if msgp.IsNil(bts) {
				bts, err = msgp.ReadNilBytes(bts)
				if err != nil {
					return
				}
				z.P = nil
			} else {
				if z.P == nil {
					z.P = new(InteriorNode)
				}
				bts, err = z.P.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "P")
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *InteriorNode) Msgsize() (s int) {
	s = 1 + 4 + msgp.ArrayHeaderSize
	for za0001 := range z.Kcs {
		s += 1 + 4 + msgp.BytesPrefixSize + len(z.Kcs[za0001].Key) + 6 + z.Kcs[za0001].Child.Msgsize()
	}
	s += 6 + msgp.IntSize + 2
	if z.P == nil {
		s += msgp.NilSize
	} else {
		s += z.P.Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *KC) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Key":
			z.Key, err = dc.ReadBytes(z.Key)
			if err != nil {
				err = msgp.WrapError(err, "Key")
				return
			}
		case "Child":
			err = z.Child.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Child")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *KC) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "Key"
	err = en.Append(0x82, 0xa3, 0x4b, 0x65, 0x79)
	if err != nil {
		return
	}
	err = en.WriteBytes(z.Key)
	if err != nil {
		err = msgp.WrapError(err, "Key")
		return
	}
	// write "Child"
	err = en.Append(0xa5, 0x43, 0x68, 0x69, 0x6c, 0x64)
	if err != nil {
		return
	}
	err = z.Child.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Child")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *KC) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "Key"
	o = append(o, 0x82, 0xa3, 0x4b, 0x65, 0x79)
	o = msgp.AppendBytes(o, z.Key)
	// string "Child"
	o = append(o, 0xa5, 0x43, 0x68, 0x69, 0x6c, 0x64)
	o, err = z.Child.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Child")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *KC) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Key":
			z.Key, bts, err = msgp.ReadBytesBytes(bts, z.Key)
			if err != nil {
				err = msgp.WrapError(err, "Key")
				return
			}
		case "Child":
			bts, err = z.Child.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Child")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *KC) Msgsize() (s int) {
	s = 1 + 4 + msgp.BytesPrefixSize + len(z.Key) + 6 + z.Child.Msgsize()
	return
}

// DecodeMsg implements msgp.Decodable
func (z *KCs) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0002 uint32
	zb0002, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if cap((*z)) >= int(zb0002) {
		(*z) = (*z)[:zb0002]
	} else {
		(*z) = make(KCs, zb0002)
	}
	for zb0001 := range *z {
		var field []byte
		_ = field
		var zb0003 uint32
		zb0003, err = dc.ReadMapHeader()
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		for zb0003 > 0 {
			zb0003--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				err = msgp.WrapError(err, zb0001)
				return
			}
			switch msgp.UnsafeString(field) {
			case "Key":
				(*z)[zb0001].Key, err = dc.ReadBytes((*z)[zb0001].Key)
				if err != nil {
					err = msgp.WrapError(err, zb0001, "Key")
					return
				}
			case "Child":
				err = (*z)[zb0001].Child.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, zb0001, "Child")
					return
				}
			default:
				err = dc.Skip()
				if err != nil {
					err = msgp.WrapError(err, zb0001)
					return
				}
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z KCs) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteArrayHeader(uint32(len(z)))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0004 := range z {
		// map header, size 2
		// write "Key"
		err = en.Append(0x82, 0xa3, 0x4b, 0x65, 0x79)
		if err != nil {
			return
		}
		err = en.WriteBytes(z[zb0004].Key)
		if err != nil {
			err = msgp.WrapError(err, zb0004, "Key")
			return
		}
		// write "Child"
		err = en.Append(0xa5, 0x43, 0x68, 0x69, 0x6c, 0x64)
		if err != nil {
			return
		}
		err = z[zb0004].Child.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, zb0004, "Child")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z KCs) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendArrayHeader(o, uint32(len(z)))
	for zb0004 := range z {
		// map header, size 2
		// string "Key"
		o = append(o, 0x82, 0xa3, 0x4b, 0x65, 0x79)
		o = msgp.AppendBytes(o, z[zb0004].Key)
		// string "Child"
		o = append(o, 0xa5, 0x43, 0x68, 0x69, 0x6c, 0x64)
		o, err = z[zb0004].Child.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, zb0004, "Child")
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *KCs) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0002 uint32
	zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if cap((*z)) >= int(zb0002) {
		(*z) = (*z)[:zb0002]
	} else {
		(*z) = make(KCs, zb0002)
	}
	for zb0001 := range *z {
		var field []byte
		_ = field
		var zb0003 uint32
		zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		for zb0003 > 0 {
			zb0003--
			field, bts, err = msgp.ReadMapKeyZC(bts)
			if err != nil {
				err = msgp.WrapError(err, zb0001)
				return
			}
			switch msgp.UnsafeString(field) {
			case "Key":
				(*z)[zb0001].Key, bts, err = msgp.ReadBytesBytes(bts, (*z)[zb0001].Key)
				if err != nil {
					err = msgp.WrapError(err, zb0001, "Key")
					return
				}
			case "Child":
				bts, err = (*z)[zb0001].Child.UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, zb0001, "Child")
					return
				}
			default:
				bts, err = msgp.Skip(bts)
				if err != nil {
					err = msgp.WrapError(err, zb0001)
					return
				}
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z KCs) Msgsize() (s int) {
	s = msgp.ArrayHeaderSize
	for zb0004 := range z {
		s += 1 + 4 + msgp.BytesPrefixSize + len(z[zb0004].Key) + 6 + z[zb0004].Child.Msgsize()
	}
	return
}
